apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cell-3
  labels:
    app: nginx-cell-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cell-3
  template:
    metadata:
      labels:
        app: nginx-cell-3
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cell-3
spec:
  selector:
    app: nginx-cell-3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
