apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-router
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: python-router
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  metricRelabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLable: app
