apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cell-1
  labels:
    app: nginx-cell-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cell-1
  template:
    metadata:
      labels:
        app: nginx-cell-1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cell-1
spec:
  selector:
    app: nginx-cell-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
